# Generated by Django 5.0.4 on 2024-04-11 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='plantregistry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Nombre de la planta')),
                ('light', models.CharField(choices=[('light1', 'Sol'), ('light2', 'Sombra'), ('light3', 'Media sombra')], max_length=250, verbose_name='Luz necesaria')),
                ('irrigation', models.CharField(max_length=250, verbose_name='Riego necesario')),
                ('alto', models.CharField(max_length=250, verbose_name='Altura promedio máxima')),
            ],
        ),
    ]
