# Generated by Django 5.0.4 on 2024-04-11 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantregistry',
            name='alto',
            field=models.CharField(blank=True, max_length=250, verbose_name='Altura promedio máxima'),
        ),
        migrations.AlterField(
            model_name='plantregistry',
            name='irrigation',
            field=models.CharField(blank=True, max_length=250, verbose_name='Riego necesario'),
        ),
        migrations.AlterField(
            model_name='plantregistry',
            name='light',
            field=models.CharField(blank=True, choices=[('light1', 'Sol'), ('light2', 'Sombra'), ('light3', 'Media sombra')], max_length=250, verbose_name='Luz necesaria'),
        ),
        migrations.AlterField(
            model_name='plantregistry',
            name='name',
            field=models.CharField(blank=True, max_length=250, verbose_name='Nombre de la planta'),
        ),
    ]
