# Generated by Django 5.0.4 on 2024-04-11 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plantas', '0002_alter_plantregistry_alto_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plantregistry',
            old_name='alto',
            new_name='height',
        ),
        migrations.AlterModelTable(
            name='plantregistry',
            table='Registry',
        ),
    ]
