# Generated by Django 5.0.4 on 2024-04-11 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantas', '0003_rename_alto_plantregistry_height_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantregistry',
            name='light',
            field=models.CharField(blank=True, choices=[('Sol', 'sol'), ('Sombra', 'sombra'), ('Media sombra', 'media sombra')], max_length=250, verbose_name='Luz necesaria'),
        ),
    ]
